server:
  port: 9003

spring:
  application:
    name: api-gateway

##GATEWAY CONFIGURATION

  cloud:
    gateway:
      routes:
        ##service1
        - id: service1
          uri: lb://SERVICE1
          predicates:
            - Path=/service1/**
          filters:
            - StripPrefix=1

        ##service2
        - id: service2
          uri: lb://SERVICE2
          predicates:
            - Path=/service2/**
          filters:
            - StripPrefix=1


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: gateway
